version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  assignees:
  - chadjvw
  versioning-strategy: increase
  ignore:
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.9.0
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.7.0
    - 2.9.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
    - 2.9.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.13.1
    - 2.15.0
  - dependency-name: gatsby
    versions:
    - 2.29.3
    - 2.31.1
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.7.0
    - 3.9.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.7.1
    - 3.9.0
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.11.0
    - 2.9.0
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.166
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
