[build.environment]
  YARN_FLAGS = "--pure-lockfile --verbose"
  YARN_VERSION = "1.21.1"
  GIT_LFS_ENABLED = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, s-max-age=31536000"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=31536000"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=31536000"
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"
